#FROM tensorflow/tensorflow:latest-gpu-py3-jupyter
FROM tensorflow/tensorflow:latest-py3-jupyter

copy  ./assets/amazon_support_tweets.pkl amazon_support_tweets.pkl
#copy  ./assets/embeddings.npy embeddings.npy
copy  ./assets/Knackathon-Text-Search.ipynb Knackathon-Text-Search.ipynb